apiVersion: batch/v1
kind: Job
metadata: 
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Bonjour le monde! Ceci est un Job Kubernetes"]
      restartPolicy: Never
  backoffLimit: 4